import type { Job } from '../../shared/types.ts';

// Fictional data is served ONLY by the localhost UI-test server, never by the public application.
export const fixtureJobs: Job[] = [
  {
    id: 'a'.repeat(64),
    title: 'Data Analyst Intern',
    company: 'Alif Labs',
    location: 'Dubai, UAE',
    workplace: 'hybrid',
    remoteRegion: null,
    employmentType: 'internship',
    sourceUrl: 'https://example.org/alif/careers/data-analyst',
    applyUrl: 'https://example.org/alif/apply/data-analyst',
    requisitionId: 'TEST-001',
    description:
      'You’ll analyse product data to uncover insights and support business decisions.\nWork with cross-functional teams to build reports and explore new data opportunities.',
    requirements: [
      'Currently studying a related degree',
      'Working knowledge of SQL and spreadsheets',
    ],
    salary: null,
    postedAt: null,
    deadline: null,
    checkedAt: new Date().toISOString(),
    sponsorship: 'not-stated',
    evidence: [
      {
        field: 'student eligibility',
        text: 'Open to current students in a related degree.',
        sourceUrl: 'https://example.org/alif/careers/data-analyst',
      },
    ],
    availability: 'open',
    match: {
      tier: 'Strong match',
      reasons: [
        'Role matches your search',
        'SQL appears in the requirements',
        'Open to current students',
      ],
      score: 90,
    },
  },
  {
    id: 'b'.repeat(64),
    title: 'Graduate Business Analyst',
    company: 'Northstar Digital',
    location: 'Abu Dhabi, UAE',
    workplace: 'onsite',
    remoteRegion: null,
    employmentType: 'graduate',
    sourceUrl: 'https://example.org/northstar/careers/analyst',
    applyUrl: 'https://example.org/northstar/apply/analyst',
    requisitionId: 'TEST-002',
    description: 'Support a graduate team with business research and analysis.',
    requirements: ['A recent business or analytics degree'],
    salary: { text: 'AED 8,000–10,000 monthly', currency: 'AED', period: 'month' },
    postedAt: null,
    deadline: null,
    checkedAt: new Date().toISOString(),
    sponsorship: 'unavailable',
    evidence: [],
    availability: 'open',
    match: {
      tier: 'Good match',
      reasons: ['Graduate opportunity', 'Relevant analytical skills'],
      score: 70,
    },
  },
  {
    id: 'c'.repeat(64),
    title: 'Junior Data Analyst',
    company: 'Atlas Works',
    location: 'Remote · EMEA only',
    workplace: 'remote',
    remoteRegion: 'EMEA',
    employmentType: 'entry-level',
    sourceUrl: 'https://example.org/atlas/careers/analyst',
    applyUrl: 'https://example.org/atlas/apply/analyst',
    requisitionId: 'TEST-003',
    description: 'An entry-level data role restricted to EMEA.',
    requirements: ['SQL and analytical thinking', 'Must reside in EMEA'],
    salary: null,
    postedAt: null,
    deadline: null,
    checkedAt: new Date().toISOString(),
    sponsorship: 'not-stated',
    evidence: [],
    availability: 'open',
    match: {
      tier: 'Possible match',
      reasons: ['SQL mentioned', 'Check the EMEA location requirement'],
      score: 50,
    },
  },
];
